import type { Metadata } from "next";

import localFont from "next/font/local";
import "./globals.css";
import   Nevigation from "@/components/nevigation";
import { Footer } from "@/components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "book webiste",
  description: "Generated by create next app",
  verification: {
    google: "TcDi97Qwevm-gVUC_zrpGUNhaoUWshRAQf_QqhawEEM",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nevigation/>
        {children}
      <Footer/>
      </body>
    </html>
  );
}
